
# Project Euler - Problem 2

# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

# 1st attempt

fibonacci = [0,1]

for num in range(2,34):
    fibonacci.append(fibonacci[num-1] + fibonacci[num-2])

print fibonacci
